export const EventData = [
    {
      id: 1,
      name: "Event 1",
      description: "Event 1 description",
      month: "January",
      day: "1",
      year: "2021",
    },
    {
      id: 2,
      name: "Event 2",
      description: "Event 2 description",
      month: "February",
      day: "15",
      year: "2021",
    },
    {
      id: 3,
      name: "Event 3",
      description: "Event 3 description",
      month: "March",
      day: "10",
      year: "2021",
    },
    {
      id: 4,
      name: "Event 4",
      description: "Event 4 description",
      month: "April",
      day: "20",
      year: "2021",
    },
    {
      id: 5,
      name: "Event 5",
      description: "Event 5 description",
      month: "May",
      day: "5",
      year: "2021",
    },
    {
      id: 6,
      name: "Event 6",
      description: "Event 6 description",
      month: "June",
      day: "30",
      year: "2021",
    },
    {
      id: 7,
      name: "Event 7",
      description: "Event 7 description",
      month: "July",
      day: "7",
      year: "2021",
    },
    {
      id: 8,
      name: "Event 8",
      description: "Event 8 description",
      month: "August",
      day: "25",
      year: "2021",
    },
    {
      id: 9,
      name: "Event 9",
      description: "Event 9 description",
      month: "September",
      day: "12",
      year: "2021",
    },
    {
      id: 10,
      name: "Event 10",
      description: "Event 10 description",
      month: "October",
      day: "3",
      year: "2021",
    },
  ];
  